services:
  api:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile.dev
    ports:
      - '3000:3000'
      - '9229:9229'
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
      - ../jest.config.js:/app/jest.config.js
      - ../tsconfig.json:/app/tsconfig.json
      - ../eslint.config.mjs:/app/eslint.config.mjs
      - ../package.json:/app/package.json
      - /app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - student-blogging-dev-network

  mongodb:
    image: mongo:7.0-jammy
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb-dev-data:/data/db
    networks:
      - student-blogging-dev-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 20s
      timeout: 20s
      retries: 20
      start_period: 50s

volumes:
  mongodb-dev-data:
    driver: local

networks:
  student-blogging-dev-network:
    driver: bridge
